package bj.wwHunter.v1.model;
// Generated 07.04.2015 16:41:45 by Hibernate Tools 3.2.1.GA


import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Gameevents generated by hbm2java
 */
public class Gameevents  implements java.io.Serializable {


     private Integer id;
     private Date dateTimeEvent;
     private int idVictim;
     private int idHunter;
     private EventState label;
     private String stringDate;

    public Gameevents() {
    }

    public Gameevents(Date dateTimeEvent, int idVictim, int idHunter, EventState label) {
       this.dateTimeEvent = dateTimeEvent;
       this.idVictim = idVictim;
       this.idHunter = idHunter;
       this.label = label;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDateTimeEvent() {
        return this.dateTimeEvent;
    }
    
    public void setDateTimeEvent(Date dateTimeEvent) {
        this.dateTimeEvent = dateTimeEvent;
    }
    public int getIdVictim() {
        return this.idVictim;
    }
    
    public void setIdVictim(int idVictim) {
        this.idVictim = idVictim;
    }
    public int getIdHunter() {
        return this.idHunter;
    }
    
    public void setIdHunter(int idHunter) {
        this.idHunter = idHunter;
    }
    public String getLabel() {
        return this.label.toString();
    }
    
    public void setLabel(String label) {
        this.label = EventState.valueOf(label);
    }

    public EventState getLbl() {
        return this.label;
    }
    
    public void setLabel(EventState label) {
        this.label = label;
    }

    public String getStringDate(){
        
        
        SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
        stringDate = df.format(getDateTimeEvent());
        
        return stringDate;
    }

}


