package bj.wwHunter.v1.model;
// Generated 07.04.2015 16:41:45 by Hibernate Tools 3.2.1.GA

import java.io.UnsupportedEncodingException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Gamers generated by hbm2java
 */
public class Gamers implements java.io.Serializable {

    private Integer id;
    private String nickName = "";
    private String lastName = "";
    private String firstName = "";
    private GamerSexState sex;
    private String birthday = "";
    private String photoPath = "";
    private String whiteZones = "";
    private String phone = "";
    private String email = "";
    private String lifeCode = "";
    private Date dateTimeImmunitet;
    private int idVictim;
    private GamerState status = GamerState.NOTACTIVE;
    String firstLastNames;
    String photo1;
    String photo2;
    String stringSex;
    String stringWhiteZones;
    String stringDateTimeImmunitet;
    String fName;
    String lName;

    public Gamers() {
    }

    public Gamers(String nickName, String lastName, String firstName, GamerSexState sex, String birthday, String photoPath, String whiteZones, String phone, String email, String lifeCode, Date dateTimeImmunitet, int idVictim, GamerState status) {
        this.nickName = nickName;
        this.lastName = lastName;
        this.firstName = firstName;
        this.sex = sex;
        this.birthday = birthday;
        this.photoPath = photoPath;
        this.whiteZones = whiteZones;
        this.phone = phone;
        this.email = email;
        this.lifeCode = lifeCode;
        this.dateTimeImmunitet = dateTimeImmunitet;
        this.idVictim = idVictim;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getLastName() {

        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {

        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSex() {
        return this.sex.toString();
    }

    public void setSex(String sex) {
        this.sex = GamerSexState.valueOf(sex);
    }

    public GamerSexState getSx() {
        return this.sex;
    }

    public void setSex(GamerSexState sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return this.birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getPhotoPath() {
        return this.photoPath;
    }

    public void setPhotoPath(String photoPath) {
        this.photoPath = photoPath;
    }

    public String getWhiteZones() {
        return this.whiteZones;
    }

    public void setWhiteZones(String whiteZones) {
        this.whiteZones = whiteZones;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLifeCode() {
        return this.lifeCode;
    }

    public void setLifeCode(String lifeCode) {
        this.lifeCode = lifeCode;
    }

    public Date getDateTimeImmunitet() {
        return this.dateTimeImmunitet;
    }

    public void setDateTimeImmunitet(Date dateTimeImmunitet) {
        this.dateTimeImmunitet = dateTimeImmunitet;
    }

    public int getIdVictim() {
        return this.idVictim;
    }

    public void setIdVictim(int idVictim) {
        this.idVictim = idVictim;
    }

    public String getStatus() {
        return this.status.toString();
    }

    public void setStatus(String status) {
        this.status = GamerState.valueOf(status);
    }

    public GamerState getStts() {
        return this.status;
    }

    public void setStatus(GamerState status) {
        this.status = status;
    }

    public String getFirstLastNames() {
        firstLastNames = getFirstName() + " " + getLastName();
        try {
            firstLastNames = new String((firstLastNames).getBytes("latin1"), "cp1251");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Gamers.class.getName()).log(Level.SEVERE, null, ex);
        }


        return firstLastNames;
    }

    public String getPhoto1() {

        photo1 = getPhotoPath().split(";")[0].substring(getPhotoPath().split(";")[0].lastIndexOf("\\") + 1);

        return photo1;
    }

    public String getPhoto2() {

        photo2 = getPhotoPath().split(";")[1].substring(getPhotoPath().split(";")[1].lastIndexOf("\\") + 1);

        return photo2;
    }

    public String getStringSex() {

        if (sex == GamerSexState.MALE) {
            stringSex = "мужской";
        } else {
            stringSex = "женский";
        }


        return stringSex;
    }

    public String getStringWhiteZones() {
        
        stringWhiteZones = getWhiteZones();
        try {
            stringWhiteZones = new String(stringWhiteZones.getBytes("latin1"),"cp1251");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Gamers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return stringWhiteZones;
    }

    public String getStringDateTimeImmunitet() {
        
        stringDateTimeImmunitet = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(getDateTimeImmunitet());
        
        return stringDateTimeImmunitet;
    }

    public void setStringDateTimeImmunitet(String stringDateTimeImmunitet) {
        try {
            this.dateTimeImmunitet = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").parse(stringDateTimeImmunitet);
        } catch (ParseException ex) {
            Logger.getLogger(Gamers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    public String getfName() {
        try {
            fName = new String(getFirstName().getBytes("latin1"),"cp1251");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Gamers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return fName;
    }

    public String getlName() {
        try {
            lName = new String(getLastName().getBytes("latin1"),"cp1251");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Gamers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return lName;
    }
    
    
    
    
    
    
    
}
