package bj.wwHunter.v1.model;
// Generated 07.04.2015 16:41:45 by Hibernate Tools 3.2.1.GA


import java.io.UnsupportedEncodingException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * News generated by hbm2java
 */
public class News  implements java.io.Serializable {


     private Integer id;
     private String textNews;
     private NewState statusNews;
     private Date dateTimeNews;
     private String stringDate;
     private String encodedTextNews;

    public News() {
    }

    public News(String textNews, NewState statusNews, Date dateTimeNews) {
       this.textNews = textNews;
       this.statusNews = statusNews;
       this.dateTimeNews = dateTimeNews;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTextNews() {
        return this.textNews;
    }
    
    public void setTextNews(String textNews) {
        this.textNews = textNews;
    }
    public String getStatusNews() {
        return this.statusNews.toString();
    }
    
    public void setStatusNews(String statusNews) {
        this.statusNews = NewState.valueOf(statusNews);
    }
    
    public NewState getStsNews() {
        return this.statusNews;
    }
    
    public void setStatusNews(NewState statusNews) {
        this.statusNews = statusNews;
    }
    
    public Date getDateTimeNews() {
        return this.dateTimeNews;
    }
    
    public void setDateTimeNews(Date dateTimeNews) {
        this.dateTimeNews = dateTimeNews;
    }

    public String getStringDate(){
        
        
        SimpleDateFormat df = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
        stringDate = df.format(getDateTimeNews());
        return stringDate;
    }

    public String getEncodedTextNews() {
        encodedTextNews = "";
        try {
            encodedTextNews = new String(getTextNews().getBytes("latin1"), "cp1251");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(News.class.getName()).log(Level.SEVERE, null, ex);
        }
        return encodedTextNews;
    }

    
    

}


